version: '3'
services:
  h1:
    image: host
    container_name: h1
    privileged: true
    build:
      context: .
      dockerfile: host.Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      R1h1br:
        ipv4_address: 172.18.0.3
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      ip route del default 
      ip route add default via 172.18.0.2
      sleep infinity
  R1:
    image: opencord/quagga
    container_name: R1
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      R1h1br:
        ipv4_address: 172.18.0.2
    volumes:
      - ./config/daemons:/etc/quagga/daemons
      - ./config/R1/zebra.conf:/etc/quagga/zebra.conf
      - ./config/R1/bgpd.conf:/etc/quagga/bgpd.conf
    entrypoint: ["/usr/bin/supervisord"]

networks:
  R1h1br:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16